### ISSUE TITLE
Инструкция по созданию образа Docker-образа не работает

### ISSUE THREAD

**Issue by lounres** [Biryukov239/matrix-multiplication-kotlin#1]
Я работаю под Windows 10. Поэтому строка `cd /home/opencl_installer && l_opencl_p_18.1.0.015/install.sh` создаёт ошибку. Плюс, в WSL она тоже не работает. Правильно я понимаю, что эта операция должна производится в консоли контейнера?

**Comment by Biryukov239** [comment]
Здравствуйте! Да, эта операция производится в консоли

**Comment by lounres** [comment]
Хорошо. У меня получилось пройти всю инструкцию. Только я не понял, как "можно лего подключиться из какой-нибудь ide". И не понял, зачем этот образ, если в нём нет ни одного файла нашего проекта.

**Comment by Biryukov239** [comment]
Как подключиться, наприме из idea, со всеми красками и подробностями описано вот тут https://www.jetbrains.com/help/idea/running-a-java-app-in-a-container.html. Зачем нужен: в данном случае(как часто делается) докер предоставляет среду исполнения, а не просто контейнер для кода, внутри этого докера можно запускать совсем разные проекты, используещие opencl. Когда вы подключаетесь из  какой-то ide, файлы проекта сами монтируются в докер и там же запускаются. P.S. это можно сделать и явно своими руками из терминала и запускать все там же из терминала докера

**Comment by lounres** [comment]
Понял. Спасибо за пояснение! Не знал такого.
