### ISSUE TITLE
Не идемпотентные геттеры — антипаттерн

### ISSUE THREAD

**Issue by lounres** [Biryukov239/matrix-multiplication-kotlin#12]
У Вас `GPUMultiplier.Companion.defaultDevice` определён с геттером, который выполняет сложную работу. Если он не идемпотентный, то его стоить заменить на функцию `getDefaultDevice`. Иначе лучше использовать `by lazy { ... }`.

**Comment by Biryukov239** [comment]
Заменил.

**Comment by lounres** [comment]
Ага. Лучше, честно говоря, делать через `lazy`, что по сто раз не вычислять одно и то же.
