### ISSUE TITLE
Проверка входных данных на корректность

### ISSUE THREAD

**Issue by lounres** [Biryukov239/matrix-multiplication-kotlin#15]
Совсем забыл. По заданию нужно ещё проверить корректность входных данных. Т.е. чтобы не было, что пользователь сначала вводит размеры 2, 2 и 2, а потом вводит матрицу 1⨯3. И при ошибке нужно напечатать вменяемое сообщение.

**Comment by Biryukov239** [comment]
Исправил.

**Comment by lounres** [comment]
Хорошо. Только во второй проверке при выводе сообщения в stderr должно быть не произведение `firstColumnCount * secondColumnCount` вместо `firstColumnCount * firstRowCount`.

Плюс, на Вашем месте я бы воспользовался бы интерполяцией. Но можно в принципе и так (через `+`).

**Comment by Biryukov239** [comment]
Исправил.

**Comment by lounres** [comment]
Теперь отлично!
