### ISSUE TITLE
Лишняя переменная `firstColumnCount`?

### ISSUE THREAD

**Issue by lounres** [Biryukov239/matrix-multiplication-kotlin#16]
В классе `MultiplierBasedOnCPU` в конструкторе определяется параметр `firstColumnCount`, который нигде не используется. Стоит либо заменить `secondMatrix.size / secondColumnCount` и `firstMatrix.size / firstRowCount` на него, либо убрать этот параметр.

**Comment by Biryukov239** [comment]
Исправил.

**Comment by lounres** [comment]
Забыли избавиться от деления в `calculate` (первая же строчка). Но ладно, это не страшно.
