### ISSUE TITLE
Нечитаемые названия переменных

### ISSUE THREAD

**Issue by lounres** [Biryukov239/matrix-multiplication-kotlin#3]
Я не смог сходу понять, что хранят переменные `m`, `k`, `n`, `fst`, `snd`,  Заодно сокращения в Kotlin тоже не поощряются: в добавок к предыдущему `firstMat`, `secondMat`, `resGPU`, `resCPU`. Также непонятны функции `roundUp` и `fit`. К ним можно приписать коротенькую документацию хотя бы.

**Comment by Biryukov239** [comment]
Поменял названия переменных и дописал короткую документацию к функциям.

**Comment by lounres** [comment]
Стало сильно лучше! Спасибо!

Ещё бы в `firstMat`, `secondMat` и `resultMat` были бы полностью дописаны слова, а также все эти правки применены к `CPUMultiplier` и `GPUMultiplier`, то было бы совсем замечательно.

**Comment by Biryukov239** [comment]
Вроде поправил.

**Comment by lounres** [comment]
Стало сильно лучше! Спасибо! Мне всё равно не нравятся оставшиеся сокращения `Mem` и `Opt`. Но ладно, на это я могу забить.
