### ISSUE TITLE
Ненужный повторяющийся код

### ISSUE THREAD

**Issue by lounres** [Biryukov239/matrix-multiplication-kotlin#6]
Пожалуйста, перепишите [это](https://github.com/Biryukov239/matrix-multiplication-kotlin/blob/8edf518d26bedc750d7298fc8d87eb155f487470/src/main/kotlin/multiplication/Kernels.kt#L105-L173) с использованием цикла и массива длины 8. Это неприятно читать. И если Вы скажите, что так производительнее, то я попрошу сначала предъявить бенчмарки. Потому что я их сделал и через `FloatArray` получается реально быстрее, чем 8 переменных.

**Comment by Biryukov239** [comment]
Здравствуйте! В первую очередь рекомендую ознакомиться с README проекта, там написано, что умножение происходит на видеокарте и с использованием библиотеки aparapi. Код который находится внутри метода run конвертируется средствами aparapi в код для видеокарты и исполняется этот код именно что на видеокарте. Это не java и не kotlin код в привычном понимании, его надо писать так, чтобы его можно было потом сконвертировать под opencl. В частности, внутри метода run нельзя использовать new, иначе говоря, массив создать нельзя, что явно и четко прописано в документации aparapi 

Если вы создали массив и говорите, что на ваших бенчмарках все работает быстрее, очень прошу вас прислать этот код, а также прикрепить, как и где вы его запускали. Отмечу, что в версии по умолчанию используется наивный алгоритм перемножения и  этот kernel не запускается, отчего может показаться, что версия с массивом работает, но, увы, new внутри run запрещен в aparapi
https://aparapi.com/documentation/kernel-guidelines.html

**Comment by lounres** [comment]
Прошу прощения, я сравнивал скорость работы маленького отрывка на JVM, а не всего вместе. Теперь я понял, что используется подмножество байт-кода JVM.

Хотя всё равно остаётся глупый вопрос: неужто при создании `Kernel` нельзя выделить массив длины 8, в начале `run` его чистить, а потом использовать как есть? Интересно, что будет быстрее (ведь на JVM быстрее именно массив).

**Comment by Biryukov239** [comment]
Смотрите, какое тут дело. Внутри kernel.run() массив создавать нельзя, так как запрещает aparapi. Можно создать его вне kernel.run, это правда, но это будет существенно медленее. Тут уже причины кроются в физическому устройстве видеокарт. У видеокарты есть локальная память: она делится между потоками warp'a, т е на nvidia между 32 потоками, на amd между 64 потоками(в aparapi это то что аннотировано @Local). Запросы к локальной памяти работают в разы быстрее чем к глобальной, про что и второй kernel(который with local mem optimization), но также у каждого потока, который запускается на видеокарте(их обычно очень много, тысячи и десятки тысяч) есть немного своей памяти(но очень мало), которой владеет только он и другие потоки ей не пользуются, она еще быстрее локальной памяти. Поэтому какие-то алгоритмы стараются делать так, чтобы часть обращей был именно к этой памяти(это буквально регистры и к ним обращение всегда очень и очень быстрое). В этой памяти хранятся все переменные, созданные внутри метода run. В частности и те восемь переменных acc. И обращение к ним существенно быстрее не только чем, обращение к глобальной памяти, но и чем обращение к локальной(аннотированной @Local). 

Конечно, в самом opencl без проблем можно создать массив, flot acc[8], и все будет работать и можно будет проходить по нему циклом, но тут проблема именно в том, что мы пишем не на чистом opencl, а на джаве и приходится иногда прибегать к таким ухищрениям . Конечно, выглядит это некрасиво, но из-за особенностей программирования на видеокарте, к сожалению, в aparapi с этим ничего нельзя сделать, не теряя производителься

P.S. сама WorkPerThread optimization кернела в том, что мы загружаем часть локальной памяти себе в регистры(которые намного быстрее), а потом уже внутри потока работает с ними, с одной стороны балансируя вычислительную нагрузку, которую обрабатывает поток и нагрузку, которая у нас есть от запросов к памяти. Умножение матриц на видеокарте - задача, в которой самая медленная часть - это обращения к памяти, что мы и стараемся оптимизировать. 

И касательно бенчмарков, провести их на aparapi тоже довольно трудно, потому что запуск кода на видеокарте состоит не только из создания и компиляции кернела, нужно также создать work range. opencl context и много других вещей, который aparapi делает сам, упрощая нам жизнь, но которые нельзя из-за этого отделить от aparapi и от нашего кернела, чтобы корректно замерить, на что и сколько уходит времени. В прочем, например, на с++ можно без  проблем сделать честный бенчмарк, вот небольшие результаты, где сравнивается CPU версия и разные алгоритмы на GPU.
![example](https://github.com/Biryukov239/matrix-multiplication-kotlin/assets/79896469/61375836-9912-499a-8af3-726bfc0d414f)

**Comment by lounres** [comment]
Понял. Спасибо за разъяснение!
