### ISSUE TITLE
Лишняя нулябельность в конструккторах `CPUMultiplier` и `GPUMultiplier`

### ISSUE THREAD

**Issue by lounres** [Biryukov239/matrix-multiplication-kotlin#8]
Вы зачем-то в коде в итоге сначала кастите `firstMat: FloatArray` к типу `FloatArray?` (при подстановке в конструктор), а потом насильно (через `!!`) кастите назад. Зачем? Это же бесполезно и ломает надёжность системы типов.

**Comment by Biryukov239** [comment]
Исправил.

**Comment by lounres** [comment]
Класс!
