### ISSUE TITLE
Не используйте `Pair` кроме как для мап

### ISSUE THREAD

**Issue by lounres** [Biryukov239/matrix-multiplication-kotlin#9]
Лучше заведите, пожалуйста специальный data-класс, названия которого и его элементов будет объяснять, что они хранят. Иначе всегда можно с недоумением смотреть на пару, не понимаю, что она значит, а также путать, что храниться первым, а что — вторым.

**Comment by Biryukov239** [comment]
Создал data-класс `Program`.

**Comment by lounres** [comment]
Так хорошо! Спасибо!
